### ISSUE TITLE
1h17m video ends after around 40 minutes.

### ISSUE THREAD

**Issue by maitra** [rooty0/ffmpeg_video_cutter#1]
Here is my profile yaml file:

```
input: "zoom.mp4"
output: "zoom_0_cut.mp4"
# You can use "delete" to delete frames for provided time or
#  "select" to keep frames for selected time and delete everything else
# You can NOT use both!
cut_method: delete
timeframe:  # select what scenes you want to keep, you can use "start"/"end" keywords to tag first and last frame
  - from: 7m48s
    to: 9m39s
  - from: 16m5s
    to: 23m12s
  - from: 49m15s
    to: 50m24s
  - from: 1h7m45s
    to: end

```
I use: 

`./cut.py --profile profile_example.yaml`
However, the resulting video is 40m17s long. Even if I tried with the select method (and an appropriately changed yaml.) Is there a limit to the length of the video? If so, how may I change it?

**Comment by rooty0** [comment]
hey @maitra , my apologies, I've just seen this, didn't get a notification for some reason... did you figure out? Is this still an issue?

**Comment by maitra** [comment]
> hey @maitra , my apologies, I've just seen this, didn't get a notification for some reason... did you figure out? Is this still an issue?

No problem, I hacked together a python script that uses ffmpeg and was able to get a workaround. I can try this again to see if the problem still persists. Thanks!

**Comment by rooty0** [comment]
prob related to this https://github.com/rooty0/ffmpeg_video_cutter/pull/3/files
